build-all:
  # non-simd version
  cargo build --release --target wasm32-unknown-unknown --no-default-features
  wasm-bindgen ./target/wasm32-unknown-unknown/release/*.wasm --browser --remove-producers-section --out-dir ./build/no_simd
  wasm-opt ./build/no_simd/wasm_bg.wasm -g -O4 --enable-nontrapping-float-to-int --precompute-propagate --fast-math --detect-features --strip-dwarf -c -o ./build/no_simd/wasm_bg.wasm

build:
  RUSTFLAGS="-Ctarget-feature=+simd128" cargo build --release --target wasm32-unknown-unknown
  wasm-bindgen ./target/wasm32-unknown-unknown/release/*.wasm --browser --remove-producers-section --out-dir ./build/simd
  wasm-opt ./build/simd/wasm_bg.wasm -g -O4 --enable-simd --enable-nontrapping-float-to-int --precompute-propagate --fast-math --detect-features --strip-dwarf -c -o ./build/simd/wasm_bg.wasm

debug:
  cargo build
  wasm-bindgen ./target/wasm32-unknown-unknown/debug/*.wasm --browser --remove-producers-section --out-dir ./build/simd
