build:
  cargo build --release --target wasm32-unknown-unknown
  wasm-bindgen ./target/wasm32-unknown-unknown/release/*.wasm --browser --remove-producers-section --out-dir .
  wasm-opt ./wasm_bg.wasm -g -O4 --enable-simd --enable-nontrapping-float-to-int --precompute-propagate --fast-math --detect-features --strip-dwarf -c -o ./wasm_bg.wasm
